server:
  hub:
    addr: "tcp://0.0.0.0:24160"
  restful:
    addr: "0.0.0.0:24162"
    base_path: "/api"
    base_path_callback: "/callback"
session:
  expiration: 30
logging:
  redirect: "file"
  level: "info"
  output: "/tmp/syspulse_server.log"
  maxAge: 14
  maxSize: 10
  maxBackups: 3
storage:
  db:
    host: "192.168.26.102"
    port: 3306
    database: "syspulse"
    user: "syspulse"
    password: "123qweASD"
  graph_db:
    endpoints:
      - "http://192.168.26.101:8529"
    user: "root"
    password: "123qweASD"
    db_name: "syspulse"
  file_server:
    endpoint: "192.168.26.105:9000"
    access_key: "env:FS_ACCESS_KEY"
    secret_key: "env:FS_SECRET_KEY"
    useSSL: false
  file:
    path: "/tmp"
cache:
  host: "192.168.26.103"
  port: 6379
  index: 0
trigger_cfg: "/app/syspulse/config/trigger.yaml"